### ISSUE TITLE
Can't require package (v5.0.1)

### ISSUE THREAD

**Issue by malbolged** [sindresorhus/string-width#36]
I'm trying to analyze a react app build files `source-map-explorer 'build/static/js/*.js'` , but I'm getting this error:
```
> my-project@0.0.1 analyze
> source-map-explorer 'build/static/js/*.js'

\my-project\node_modules\wrap-ansi\node_modules\string-width\index.js:3
const isFullwidthCodePoint = require('is-fullwidth-code-point');
                             ^

Error [ERR_REQUIRE_ESM]: require() of ES Module \my-project\node_modules\is-fullwidth-code-point\index.js from \my-project\node_modules\wrap-ansi\node_modules\string-width\index.js not supported.
Instead change the require of \my-project\node_modules\is-fullwidth-code-point\index.js in \my-project\node_modules\wrap-ansi\node_modules\string-width\index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (\my-project\node_modules\wrap-ansi\node_modules\string-width\index.js:3:30)
    at Object.<anonymous> (\my-project\node_modules\wrap-ansi\index.js:2:21)
    at Object.<anonymous> (\my-project\node_modules\source-map-explorer\node_modules\cliui\build\index.cjs:293:14)
    at Object.<anonymous> (\my-project\node_modules\source-map-explorer\node_modules\yargs\build\index.cjs:2861:12)
    at Object.<anonymous> (\my-project\node_modules\source-map-explorer\node_modules\yargs\index.cjs:5:30)
    at Object.<anonymous> (\my-project\node_modules\source-map-explorer\bin\cli.js:10:33) {
  code: 'ERR_REQUIRE_ESM'
}
```

might be related to this issue https://github.com/sindresorhus/string-width/issues/33

**Comment by sindresorhus** [comment]
This is a problem with `source-map-explorer` not supporting ESM, not a problem with this package.

**Comment by antoniobrandao** [comment]
@sindresorhus just want to report that unfortunately this is causing `ERR_REQUIRE_ESM` errors in quite many places, due to the interconnectedness of NPM packages, and it being in use by so many. Just as an example, Shopify applications builds fail a lot because of this (I ran into the problem).

It's not something we can fix directly because it's a dependency of a dependency of a dependency - ends up being used in large codebases that require non-ESM import ability.

I understand your reasons to make it ESM only - but when a package ends up being used so far and wide, the inevitable `ERR_REQUIRE_ESM` chaos will ensue for many.
